<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <RootNamespace>LightHashTab</RootNamespace>
    <AssemblyName>LightHashTab</AssemblyName>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <StripSymbols>true</StripSymbols>
    <OptimizationPreference>Speed</OptimizationPreference>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blake3" Version="3.0.0" />
    <PackageReference Include="System.IO.Hashing" Version="9.0.2" />
  </ItemGroup>

</Project>
